### ISSUE TITLE
API Documentation for the Tahoma system

### ISSUE THREAD

**Issue by qorron** [jbtibor/SmartThings#1]
Is there any API documentation for the Tahoma box? you seem to have a decent knowledge about it and I couldn't find anything on the net.

I don't have anything from Smartthings but I own a Tahoma box and I'm looking for a way to trigger a scenario from the network.

**Comment by jbtibor** [comment]
I haven't found an API for 3rd parties, so I'm using the ajax API from https://www.tahomalink.com.
You should be able to access it with curl and other programmatic methods.

**Comment by jbtibor** [comment]
Take a look at this as well:
https://www.somfysystems.com/products/1870264/somfy-connect-uai

**Comment by qorron** [comment]
https://www.tahomalink.com points me to the login page from where I can access my tahoma but there is no API documentation here. (unless it shows something different for you)
the somfy connect uai appears only to work with RTS and SDN devices.. mine are all IO.homecontrol, so this might not work.

**Comment by jbtibor** [comment]
There is no documentation for Tahoma API - I mean nothing public I am aware of, just copy the ajax calls issued by browser.

**Comment by qorron** [comment]
oh, the browser developer tools! now I'm feeling dumb for asking :-D
thanks a lot for pointing me in the right direction
