### ISSUE TITLE
RTS garage door not detected

### ISSUE THREAD

**Issue by Papsd** [jbtibor/SmartThings#12]
Dear Dev team,
I don't know why but the RTS garage doors are not detected.
Thanks by advance.

**Comment by jbtibor** [comment]
Hi, support for garage door controller is not implemented. It should be implemented by someone who owns such device and can test the code.

**Comment by Papsd** [comment]
Thanks a lot for your answer, I have some bases in code, so if you guide me a little I can work on it with pleasure.

Thanks a lot by advance.
