### ISSUE TITLE
Cannot add my window shade to ST

### ISSUE THREAD

**Issue by sherifsurf** [jbtibor/SmartThings#3]
Did all the steps, and after login to the marketplace somfy app, I can't see my window shade that I use to see and control in Tahoma app or web interface 

It shows 
roller shutters 
You can't currently add this "dimmed"

**Comment by jbtibor** [comment]
Where exactly do you see "You can't currently add this "dimmed""?
Please log in to https://developer.smartthings.com and open Live Logging, repeat the connection wizard then send me the log output from Somfy tab only.

**Comment by sherifsurf** [comment]
Get Outlook for Android







On Tue, Sep 26, 2017 at 8:51 PM +0400, "jbtibor" <notifications@github.com> wrote:












Where exactly do you see "You can't currently add this "dimmed""?

Please log in to https://developer.smartthings.com and open Live Logging, repeat the connection wizard then send me the log output from Somfy tab only.

**Comment by sherifsurf** [comment]
AllTaHoma® by Somfy




LogsClear




35c4b91e-f032-46c0-bc97-7dbd475ea634 9:12:47 PM: errorupdateRollerShutters(): Error: groovyx.net.http.HttpResponseException: Internal Server Error




 9:12:21 PM: infoWaiting on events...




 9:12:21 PM: infoFor past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.




 9:12:21 PM: infoThis console provides live logging of your SmartThings.








Get Outlook for Android







On Tue, Sep 26, 2017 at 9:05 PM +0400, "sherif hafez" <sherifsurf@gmail.com> wrote:




































Get Outlook for Android







On Tue, Sep 26, 2017 at 8:51 PM +0400, "jbtibor" <notifications@github.com> wrote:












Where exactly do you see "You can't currently add this "dimmed""?

Please log in to https://developer.smartthings.com and open Live Logging, repeat the connection wizard then send me the log output from Somfy tab only.

**Comment by sherifsurf** [comment]
AllTaHoma® by SomfyLogitech Harmony (Connect)Super LAN Connect




LogsClear




35c4b91e-f032-46c0-bc97-7dbd475ea634 9:12:47 PM: errorupdateRollerShutters(): Error: groovyx.net.http.HttpResponseException: Internal Server Error








Get Outlook for Android







On Tue, Sep 26, 2017 at 9:15 PM +0400, "sherif hafez" <sherifsurf@gmail.com> wrote:










AllTaHoma® by Somfy




LogsClear




35c4b91e-f032-46c0-bc97-7dbd475ea634 9:12:47 PM: errorupdateRollerShutters(): Error: groovyx.net.http.HttpResponseException: Internal Server Error




 9:12:21 PM: infoWaiting on events...




 9:12:21 PM: infoFor past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.




 9:12:21 PM: infoThis console provides live logging of your SmartThings.








Get Outlook for Android







On Tue, Sep 26, 2017 at 9:05 PM +0400, "sherif hafez" <sherifsurf@gmail.com> wrote:




































Get Outlook for Android







On Tue, Sep 26, 2017 at 8:51 PM +0400, "jbtibor" <notifications@github.com> wrote:












Where exactly do you see "You can't currently add this "dimmed""?

Please log in to https://developer.smartthings.com and open Live Logging, repeat the connection wizard then send me the log output from Somfy tab only.

**Comment by jbtibor** [comment]
Not much in the logs. Give me a few days to investigate.

**Comment by jbtibor** [comment]
I updated the SmartApp and DeviceType, please update your copy if you have time and give it another go.
If still doesn't work please enable debug logging in SmartApp settings, log in to live logging, repeat what failed and send me the logs.

**Comment by snoge** [comment]
Hi, after update can't login. After entering login next screen is empty and error at the end. Previous version was fine, but can't control from Harmony

**Comment by jbtibor** [comment]
Did you update both the SmartApp and device type handler? If not, please do.
If yes, please enable debug logging in SmartApp settings, log in to live logging, repeat what failed and send me the logs.

**Comment by snoge** [comment]
Yes, I updated both by copy paste. Then I deleted it and installed it again, same error.

from log:
d6a60c30-6fdc-4762-b154-35b142aa7aed  10:38:37: error groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.lang.Long#minus.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
[class java.lang.Character]
[class java.lang.Number] @ line 175
d6a60c30-6fdc-4762-b154-35b142aa7aed  10:38:37: debug SA 1.2.20171001: getAuthorizationHeaderValue()
d6a60c30-6fdc-4762-b154-35b142aa7aed  10:38:37: debug SA 1.2.20171001: updateRollerShutters()
d6a60c30-6fdc-4762-b154-35b142aa7aed  10:38:37: debug SA 1.2.20171001: getRollerShutterNames()
d6a60c30-6fdc-4762-b154-35b142aa7aed  10:38:37: debug SA 1.2.20171001: settingsPage()

**Comment by jbtibor** [comment]
I modified the SmartApp, please update your copy and give it a try. Thanks.
https://github.com/jbtibor/SmartThings/blob/master/Somfy/TaHoma/TaHomaBySomfy.SmartApp.groovy

**Comment by snoge** [comment]
Great job, works great and as switch for Harmony as well.
Thanks a lot.

**Comment by jbtibor** [comment]
You are welcome, thanks for helping out with error messages.
