### ISSUE TITLE
Timeout Exception when polling several Wireless Tags 

### ISSUE THREAD

**Issue by KHouse75** [jbtibor/SmartThings#5]
I have 8 wireless tags that I'm trying to read through Smartthings.  Your app will successfully read data for 4 typically and will sometimes get data for up to 6.  Anything greater than 4 devices though, I get a timeout exception.

**Error:  Exception polling devices: java.util.concurrent.TimeoutException: Execution time exceeded 20 app execution seconds: 114119933668978**

Even if I try to refresh a single device, it appears to be trying to poll all devices which then times out.

Any ideas what's causing this?  I don't know groovy that well so I'm having a hard time troubleshooting the problem.

**Comment by jbtibor** [comment]
I have time outs in other integrations too, i.e. Zapier. This is down to Wireless Tags servers.
You could try another integration too: 
https://community.smartthings.com/t/wireless-sensor-tags-integration/5259

**Comment by KHouse75** [comment]
Thanks for the info.  I looked at swanny's implementation last night as well but haven't given it a try yet.

Looks like SmartThings has a 20 second timeout for execution of code.  I'll look into this more when I have time to better understand SmartThings implementation of Groovy.
