### ISSUE TITLE
Can not finish in the app 

### ISSUE THREAD

**Issue by ttppeewee** [jbtibor/SmartThings#6]
When I try to finish the installation in the app, the last step fails. I get the following messages
"An unexpected error occurred"

**Comment by jbtibor** [comment]
Please enable debugging, open log (https://graph.api.smartthings.com/ide/logs), repeat installation, then share log. Remove any personal information before sharing.

**Comment by ttppeewee** [comment]
Her is me log
￼
All
Loft midt
TaHoma® by Somfy
ActionTiles V6 (Connect)
Logs
Clear
99b0af72-9f73-43a3-9a67-75c5f317043a 06.33.06: info checkEventStreamStatusCallback: Location Event Stream Status is STREAMING
99b0af72-9f73-43a3-9a67-75c5f317043a 06.33.06: info Checking Event Stream Status
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.46: debug SA 1.3.20180612: updateDevices(): resp.data [creationTime:1573246987000, devices:[[attributes:[], available:true, controllableName:internal:TSKAlarmComponent, creationTime:1573247383000, definition:[commands:[[commandName:alarmOff, nparams:0], [commandName:alarmOn, nparams:0], [commandName:getName, nparams:0], [commandName:off, nparams:0], [commandName:on, nparams:0], [commandName:setName, nparams:1], [commandName:refreshAlarmDelay, nparams:0], [commandName:refreshCurrentAlarmMode, nparams:0], [commandName:refreshIntrusionDetected, nparams:0], [commandName:setAlarmDelay, nparams:1], [commandName:alarmPartial1, nparams:0], [commandName:alarmPartial2, nparams:0], [commandName:setIntrusionDetected, nparams:1], [commandName:setTargetAlarmMode, nparams:1]], dataProperties:[], qualifiedName:internal:TSKAlarmComponent, states:[[qualifiedName:core:NameState, type:DataState], [qualifiedName:internal:AlarmDelayState, type:ContinuousState], [qualifiedName:internal:CurrentAlarmModeState, type:DiscreteState, values:[off, partial1, partial2, total]], [qualifiedName:internal:IntrusionDetectedState, type:DiscreteState, values:[detected, notDetected, pending, sos]], [qualifiedName:internal:TargetAlarmModeState, type:DiscreteState, values:[off, partial1, partial2, sos, total]]], type:ACTUATOR, uiClass:Alarm, widgetName:TSKAlarmController], deviceURL:internal://1222-7627-7291/alarm/0, enabled:true, label:Alarm, lastUpdateTime:1573247383000, oid:d3557403-1ba1-47e9-9505-f545791b2315, placeOID:3d854edd-01e9-47dc-9439-7a17680a47df, shortcut:false, states:[[name:core:NameState, type:3, value:alarm name], [name:internal:CurrentAlarmModeState, type:3, value:off], [name:internal:AlarmDelayState, type:1, value:30], [name:internal:TargetAlarmModeState, type:3, value:off], [name:internal:IntrusionDetectedState, type:3, value:notDetected]], type:1, uiClass:Alarm, widget:TSKAlarmController], [attributes:[], available:true, controllableName:internal:PodV2Component, creationTime:1573246987000, definition:[commands:[[commandName:getName, nparams:0...[TRUNCATED]
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.46: debug SA 1.3.20180612: updateDevices(): rollerShutters [c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16733492:[attributes:[[name:rts:diy, type:6, value:true]], available:true, controllableName:rts:RollerShutterRTSComponent, creationTime:1573248016000, definition:[commands:[[commandName:close, nparams:0], [commandName:down, nparams:0], [commandName:identify, nparams:0], [commandName:my, nparams:0], [commandName:open, nparams:0], [commandName:rest, nparams:0], [commandName:stop, nparams:0], [commandName:test, nparams:0], [commandName:up, nparams:0]], dataProperties:[[qualifiedName:core:identifyInterval, value:0]], qualifiedName:rts:RollerShutterRTSComponent, states:[], type:ACTUATOR, uiClass:RollerShutter, widgetName:UpDownRollerShutter], deviceURL:rts://1222-7627-7291/16733492, enabled:true, label:Spisestue, lastUpdateTime:1573248016000, oid:fece4749-7f1d-4f52-81ac-1179e4beccd1, placeOID:2ae79168-50d4-40fd-9459-94a81670a4a6, shortcut:false, type:1, uiClass:RollerShutter, widget:UpDownRollerShutter], c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16734212:[attributes:[[name:rts:diy, type:6, value:true]], available:true, controllableName:rts:RollerShutterRTSComponent, creationTime:1573249443000, definition:[commands:[[commandName:close, nparams:0], [commandName:down, nparams:0], [commandName:identify, nparams:0], [commandName:my, nparams:0], [commandName:open, nparams:0], [commandName:rest, nparams:0], [commandName:stop, nparams:0], [commandName:test, nparams:0], [commandName:up, nparams:0]], dataProperties:[[qualifiedName:core:identifyInterval, value:0]], qualifiedName:rts:RollerShutterRTSComponent, states:[], type:ACTUATOR, uiClass:RollerShutter, widgetName:UpDownRollerShutter], deviceURL:rts://1222-7627-7291/16734212, enabled:true, label:Soveværelse, lastUpdateTime:1573249443000, oid:cfbbdd7b-c981-48b3-a9a1-eaba6bfaca65, placeOID:446de59f-6a0a-419a-9259-e7a6984812d0, shortcut:false, type:1, uiClass:RollerShutter, widget:UpDownRollerShutter], c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7...[TRUNCATED]
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.46: debug SA 1.3.20180612: updateDevices(): rawDeviceData [c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16733492:[attributes:[[name:rts:diy, type:6, value:true]], available:true, controllableName:rts:RollerShutterRTSComponent, creationTime:1573248016000, definition:[commands:[[commandName:close, nparams:0], [commandName:down, nparams:0], [commandName:identify, nparams:0], [commandName:my, nparams:0], [commandName:open, nparams:0], [commandName:rest, nparams:0], [commandName:stop, nparams:0], [commandName:test, nparams:0], [commandName:up, nparams:0]], dataProperties:[[qualifiedName:core:identifyInterval, value:0]], qualifiedName:rts:RollerShutterRTSComponent, states:[], type:ACTUATOR, uiClass:RollerShutter, widgetName:UpDownRollerShutter], deviceURL:rts://1222-7627-7291/16733492, enabled:true, label:Spisestue, lastUpdateTime:1573248016000, oid:fece4749-7f1d-4f52-81ac-1179e4beccd1, placeOID:2ae79168-50d4-40fd-9459-94a81670a4a6, shortcut:false, type:1, uiClass:RollerShutter, widget:UpDownRollerShutter], c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16734212:[attributes:[[name:rts:diy, type:6, value:true]], available:true, controllableName:rts:RollerShutterRTSComponent, creationTime:1573249443000, definition:[commands:[[commandName:close, nparams:0], [commandName:down, nparams:0], [commandName:identify, nparams:0], [commandName:my, nparams:0], [commandName:open, nparams:0], [commandName:rest, nparams:0], [commandName:stop, nparams:0], [commandName:test, nparams:0], [commandName:up, nparams:0]], dataProperties:[[qualifiedName:core:identifyInterval, value:0]], qualifiedName:rts:RollerShutterRTSComponent, states:[], type:ACTUATOR, uiClass:RollerShutter, widgetName:UpDownRollerShutter], deviceURL:rts://1222-7627-7291/16734212, enabled:true, label:Soveværelse, lastUpdateTime:1573249443000, oid:cfbbdd7b-c981-48b3-a9a1-eaba6bfaca65, placeOID:446de59f-6a0a-419a-9259-e7a6984812d0, shortcut:false, type:1, uiClass:RollerShutter, widget:UpDownRollerShutter], c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-72...[TRUNCATED]
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.46: debug SA 1.3.20180612: getAuthorizationHeaderValueCore(): authorizationHeaderValue JSESSIONID=5070E9236C054AD5E5EEDA37D1E6AF30
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.45: debug SA 1.3.20180612: [method:POST, uri:https://www.tahomalink.com/enduser-mobile-web/enduserAPI/, path:login, headers:[Content-Type:application/x-www-form-urlencoded; charset=UTF-8]]
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.45: debug SA 1.3.20180612: getAuthorizationHeaderValue: Authorizing with server.
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.45: debug SA 1.3.20180612: getAuthorizationHeaderValue()
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.46: debug SA 1.3.20180612: getAuthorizationHeaderValueCore(): resp.data [roles:[[name:ENDUSER]], success:true]
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.45: debug SA 1.3.20180612: getAuthorizationHeaderValueCore()
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.45: debug SA 1.3.20180612: updateDevices()
c6991d70-15d0-48b1-b88d-cb53c244f56a 06.32.45: debug SA 1.3.20180612: installed(): [username:xxxx, password:xxxxcc, debugMode:true, selectedRollerShutterNames:[c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16733492, c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16734212, c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16755102, c6991d70-15d0-48b1-b88d-cb53c244f56a.rts://1222-7627-7291/16763054]]
d15886d8-43b1-4a2e-85f2-7a1887d20107 06.32.44: debug healthPoll()
 06.32.39: info Waiting on events...
 06.32.39: info For past logs for individual things go to the My Devices section, find the device and click on the Events link on the device information page.
 06.32.39: info This console provides live logging of your SmartThings.
--
Sendt fra Outlook Email App til Android onsdag, 13 november 2019, 05:33PM +01:00 fra jbtibor  notifications@github.com :

**Comment by ttppeewee** [comment]
There is a error. 
--
Sendt fra Outlook Email App til Android onsdag, 13 november 2019, 05:33PM +01:00 fra jbtibor  notifications@github.com :
