### ISSUE TITLE
RTS Blinds not updating sate when controlled from remote

### ISSUE THREAD

**Issue by adavison007** [jbtibor/SmartThings#7]
Hi, I have RTS blinds via Tahoma. When I use the remote or Alexa to open of close the blinds, your smart app does not reflect the new state? have I done something wrong, also bolster does not show the blinds in SmartThings as a device I can poll?

Please advise, appreciate any support?

**Comment by jbtibor** [comment]
Hi, RTS protocol is one way, state of devices is not reported therefore app can be out of sync at any time. Same happens if a blind or any other RTS device is operated with a remote control or Somfy app.

**Comment by adavison007** [comment]
Thanks, so when I just asked Alexa to open the blind, Somfy shows device controlled? So it does know It was controlled, so why can Tahoma not report the state back to Smart things? See bottom of picture



Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 8 Feb 2020, at 13:36, jbtibor <notifications@github.com> wrote:

Hi, RTS protocol is one way, state of devices is not reported therefore app can be out of sync at any time. Same happens if a blind or any other RTS device is operated with a remote control or Somfy app.

**Comment by jbtibor** [comment]
Alexa integration is done by Somfy so they can update their app.

> why can Tahoma not report the state back to Smart things?
This is a question to Somfy :-) But even in this case state would go out of sync if the blind is controlled with anything else than Alexa or Tahoma app/website.
